import fetch from 'node-fetch';
import uploadImage from '../lib/uploadImage.js';

let handler = async (m, { conn, text, usedPrefix, command }) => {
  if (!text)
    throw `*This command generates images from text prompts*\n\n*Example usage:*\n◉ ${usedPrefix + command} Beautiful anime girl\n◉ ${usedPrefix + command} Elon Musk in pink outfit`;

  try {
    m.reply('*Please wait, generating images...*');

    const endpoint = `https://api.gurusensei.workers.dev/dream?prompt=${encodeURIComponent(text)}`;
    const response = await fetch(endpoint);

    if (response.ok) {
      const imageBuffer = await response.buffer();
      const imgurl = await uploadImage(imageBuffer);
      const author = 'Generated by XLICON V2'; 

      await conn.sendButton(
        m.chat,
        'Here is your Result',
        author,
        imgurl,
        [['MENU', `${usedPrefix}menu`], ['WATCH ANIME', 'https://ab-streamer.vercel.app']],
        m
      );
    } else {
      throw new Error('*Image generation failed*');
    }
  } catch (error) {
    console.error(error);
    throw '*Oops! Something went wrong while generating images. Please try again later.*';
  }
};

handler.help = ['dalle'];
handler.tags = ['AI'];
handler.command = ['dalle', 'gen', 'imagine', 'openai2'];

export default handler;
